### ISSUE TITLE
Plain text API key

### ISSUE THREAD

**Issue by MuchaSsak** [POOVASOKAN/Weather-App#2]
I've noticed an `apiKey` variable in `/script.js` visible to everyone. That should be hidden in an environment variable for security purposes.

I see that your app is deployed to Netlify. If you need help using environment variables in production, you might find this article useful - https://www.netlify.com/blog/a-guide-to-storing-api-keys-securely-with-environment-variables/

As for local development purposes, you may just create a `.env` file. Don't forget to exclude it for Git. The easiest way to do that is to put `.env` in your `.gitignore` file, or use a `.gitignore` template (e.g. Node template).

**Comment by POOVASOKAN** [comment]
Sure , Thank you for the input . I appreciate it !
